services:
  - type: web
    name: searxng
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "export PYTHONPATH=. && python searx/webapp.py"
    plan: free
    branch: main