services:
  - type: web
    name: searxng
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "export PYTHONPATH=. && export SEARXNG_SETTINGS_PATH=./settings.yml && python searx/webapp.py"
    plan: free
    branch: main