use_default_settings: true
server:
  secret_key: "RenderDeploySecretKey2024"
  bind_address: "0.0.0.0"
  port: 8080
  base_url: false
  image_proxy: false
search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
ui:
  static_use_hash: false